### ISSUE TITLE
License Activation isn't working

### ISSUE THREAD

**Issue by Imaginativeone** [telerik/kendo-react-nextjs#3]
npx kendo-ui-license does nothing

**Comment by WissamProgress** [comment]
Hi, Imaginativeone,

We are aware of an issue where the license warnings and watermark persist even after license activation when running the project in development mode (using `npm run dev`).

You can resolve it by deleting the `.next` folder that stores the page cache where the licensing information is included in the cache. When running `npm run dev` again, this folder will be regenerated and the license warnings and watermark should be removed.

Please try that and let me know if this resolves the faced issue.
